### ISSUE TITLE
[device-port] [serranodsdd] Samsung S4 mini duos

### ISSUE THREAD

**Issue by rogieroudshoorn** [Halium/projectmanagement#105]
Tree: halium-7.1

- [X] Create [manifest](https://github.com/Halium/halium-devices/pull/129) 
- [X] Boot image and system image build successfully
- [X] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [x] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

Funky issue: device needs to have flashed halium-boot once; afterwards hybris-boot works as usual
Current status: LXC runs; now to actually get tests to run

**Comment by rogieroudshoorn** [comment]
When i build with CONFIG_PID_NS enabled, i get the following build error on mka hybris-boot (and systemimage):

Update: fixed by [https://github.com/rogieroudshoorn/android_kernel_samsung_msm8930-common/commit/892adf21e3912542d8264e13361e5858452fd997](url)

**Comment by rogieroudshoorn** [comment]
![photo_2018-11-04_16-03-29](https://user-images.githubusercontent.com/8288690/47965768-4afc0700-e04b-11e8-8f67-d45c9ddddcad.jpg)

Plasma boots :) Still have lots of errors in dmesg and logcat to deal with though, and scaling seems woefully incorrect.

**Comment by mahond** [comment]
Hi,

I have the LTE version.  i9195.

I would be interested to get Ubuntu touch running.

**Comment by digmorepaka** [comment]
I have a few spare serranoltexx(i9195) boards, it shouldnt be that hard to port it since it already boots on the duos. Most likely changing the kernel and some modem stuff.

**Comment by rogieroudshoorn** [comment]
Since all s4 mini's share a common lineage kernel & device it should be as easy as replacing 4 defconfig flags to get it booting on the LTE version; i think the 3G version will "just work" with what there is. 

I am nowhere near getting the modem to work anyway, and if you guys want to pitch in on the 9195, i think we'll go a lot quicker. Warning though - the kernel is so old on this device, the newer versions of plasma will probably not work (they'll require a newer kernel for systemd). UBPorts will probably be fine until they jump to 20.04.

**Comment by digmorepaka** [comment]
in a few weeks i will get parts for one of my 9195s and il be happy to test it

**Comment by Flohack74** [comment]
Any activity still here? Modem does not work because Samsung uses an incompatible RIL layer that will not work with ofonod out of the box. I fixed this for S3, and probably same stuff needs to be done for other Samsungs...

**Comment by rogieroudshoorn** [comment]
Not really, ordered a pinephone so i'd have something that is usefull for a much longer term ... still have the phone laying around somewhere if there's something you'd like to me test though!

**Comment by Flohack74** [comment]
Well interesting question first, can you look in your device tree if there is a *RIL*.java class to be found (* means something could be written before or after the word RIL). You might want to search in the original tree since Halium tends to strip out those files.
